language: node_js

sudo: required
node_js: 
  - 7.9.0

cache:
  directories:
    - node_modules

branches:
  only:
    - startup 

before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "email"
  - git config user.email "pwd"
  - sed -i "s/gh_token/${gh_token}/g" ./_config.yml
  - hexo deploy